[package]
name = "reqwest-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.3.1"
mime_guess = "2.0.5"
reqwest = "0.12.22"
reqwest-middleware = { version = "0.4.2", features = ["json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
url = "2.5.4"
